import menus from "@/assets/portfolio-menus.jpg.asset.json";
import stickersMarca from "@/assets/portfolio-stickers-marca.jpg.asset.json";
import carpetas from "@/assets/portfolio-carpetas.jpg.asset.json";
import troquelados from "@/assets/portfolio-troquelados.jpg.asset.json";
import banner from "@/assets/portfolio-banner.jpg.asset.json";
import microperforado from "@/assets/portfolio-microperforado.jpg.asset.json";
import rotulacion from "@/assets/portfolio-rotulacion.jpg.asset.json";
import tarjetas from "@/assets/portfolio-tarjetas.jpg.asset.json";
import backToSchool from "@/assets/portfolio-back-to-school.jpg.asset.json";
import standFotos from "@/assets/portfolio-stand-fotos.jpg.asset.json";
import espejoStickers from "@/assets/portfolio-espejo-stickers.jpg.asset.json";
import menuPvc from "@/assets/portfolio-menu-pvc.jpg.asset.json";
import figuraPvc from "@/assets/portfolio-figura-pvc.jpg.asset.json";
import pvcGaby from "@/assets/portfolio-pvc-gaby.jpg.asset.json";
import figurasMundial from "@/assets/portfolio-figuras-mundial-hd.jpg.asset.json";
import banderines from "@/assets/portfolio-banderines-hd.jpg.asset.json";
import albumMama2 from "@/assets/portfolio-album-mama-2.jpg.asset.json";
import bannerCruzacalle from "@/assets/portfolio-banner-cruzacalle.jpg.asset.json";
import variedadBanners from "@/assets/portfolio-variedad-banners.jpg.asset.json";
import grabadoPapa from "@/assets/portfolio-grabado-papa.jpg.asset.json";
import camisetasPapa from "@/assets/portfolio-camisetas-papa.jpg.asset.json";
import botellasPersonalizadas from "@/assets/portfolio-botellas-personalizadas.jpg.asset.json";
import etiquetasBotellas from "@/assets/portfolio-etiquetas-botellas.jpg.asset.json";
import marcosFotos from "@/assets/portfolio-marcos-fotos.jpg.asset.json";
import cadenasGrabado from "@/assets/portfolio-cadenas-grabado.jpg.asset.json";
import boxersPersonalizados from "@/assets/portfolio-boxers.jpg.asset.json";
import calsetasPersonalizadas from "@/assets/portfolio-calsetas.jpg.asset.json";
import retrateras from "@/assets/portfolio-retrateras.jpg.asset.json";
import rompecabezas from "@/assets/portfolio-rompecabezas.jpg.asset.json";
import polaroid from "@/assets/portfolio-polaroid.jpg.asset.json";
import rollosFacturacion from "@/assets/portfolio-rollos-facturacion.jpg.asset.json";
import sublimacion from "@/assets/portfolio-sublimacion.jpg.asset.json";
import empaques from "@/assets/portfolio-empaques.jpg.asset.json";
import stickersEmpaques from "@/assets/portfolio-stickers-empaques.jpg.asset.json";
import etiquetasBebidas from "@/assets/portfolio-etiquetas-bebidas.jpg.asset.json";
import etiquetasGuifity from "@/assets/portfolio-etiquetas-guifity.jpg.asset.json";
import etiquetasCumple from "@/assets/portfolio-etiquetas-cumple.jpg.asset.json";
import servicio360 from "@/assets/portfolio-360.jpg.asset.json";
import impresionJarra from "@/assets/portfolio-impresion-jarra.jpg.asset.json";
import regalosCorporativos from "@/assets/portfolio-regalos-corporativos.png.asset.json";
import tazasSublimadas from "@/assets/portfolio-tazas-sublimadas.png.asset.json";
import calendariosCorporativos from "@/assets/portfolio-calendarios-corporativos.jpg.asset.json";
import combosCorporativos from "@/assets/portfolio-combos-corporativos.jpg.asset.json";
import camisetasHonduras from "@/assets/portfolio-camisetas-honduras.png.asset.json";
import camisetasHonduras2 from "@/assets/portfolio-camisetas-honduras-2.png.asset.json";
import fiestasPatriasCuadro from "@/assets/portfolio-fiestas-patrias-cuadro.png.asset.json";
import fiestasPatriasProceres from "@/assets/portfolio-fiestas-patrias-proceres.png.asset.json";
import stickerTroqueladoCafe from "@/assets/portfolio-sticker-troquelado-cafe.png.asset.json";

import camisetasEstampadas from "@/assets/portfolio-camisetas-estampadas.png.asset.json";
import rotulosPrevencion from "@/assets/portfolio-rotulos-prevencion.png.asset.json";
import etiquetasFoil from "@/assets/portfolio-etiquetas-foil.png.asset.json";
import grabadoLaserCoco from "@/assets/portfolio-grabado-laser-coco.png.asset.json";
import impresionCartoncillo from "@/assets/portfolio-impresion-cartoncillo.png.asset.json";
import abanicoLaser from "@/assets/portfolio-abanico-laser.png.asset.json";
import cajitasCandySticker from "@/assets/portfolio-cajitas-candy-sticker.png.asset.json";
import audioGuestbook from "@/assets/portfolio-audio-guestbook.png.asset.json";
import etiquetasGuifitiBotellas from "@/assets/portfolio-etiquetas-guifiti-botellas.png.asset.json";
import pvcBienvenidaJessie from "@/assets/portfolio-pvc-bienvenida-jessie.png.asset.json";
import cuadrosCanvas from "@/assets/portfolio-cuadros-canvas.png.asset.json";
import stickersTamanos from "@/assets/portfolio-stickers-tamanos.png.asset.json";
import fotosPersonalizadas from "@/assets/portfolio-fotos-personalizadas.png.asset.json";
import marcosPersonalizados from "@/assets/portfolio-marcos-personalizados.png.asset.json";
import esferasNavidenas from "@/assets/portfolio-esferas-navidenas.png.asset.json";
import termoStanley from "@/assets/portfolio-termo-stanley.png.asset.json";
import bolsosMama from "@/assets/portfolio-bolsos-mama.png.asset.json";
import bolsosSublimados from "@/assets/portfolio-bolsos-sublimados.png.asset.json";
import impresionLaserCapy from "@/assets/portfolio-impresion-laser-capy.jpg.asset.json";
import stickerTroqueladoBrioche from "@/assets/portfolio-sticker-troquelado-brioche.jpg.asset.json";
import snacksPersonalizados from "@/assets/portfolio-snacks-personalizados.png.asset.json";
import fotosCristal from "@/assets/portfolio-fotos-cristal.jpg.asset.json";
import termoMamaMariposas from "@/assets/portfolio-termo-mama-mariposas.jpg.asset.json";
import libretaCorazones from "@/assets/libreta-175.jpg.asset.json";
import libretaPlanner from "@/assets/libreta-177.jpg.asset.json";
import libretaFuerza from "@/assets/libreta-178.jpg.asset.json";
import libretaSalmo from "@/assets/libreta-179.jpg.asset.json";
import libretaFe from "@/assets/libreta-180.jpg.asset.json";
import libretaFuturo from "@/assets/libreta-181.jpg.asset.json";
import libretaDreams from "@/assets/libreta-182.jpg.asset.json";
import libretaEcoCover from "@/assets/libreta-183.jpg.asset.json";
import libretaEcoOpen from "@/assets/libreta-184.jpg.asset.json";
import libretaSuenaPlanea from "@/assets/libreta-suena-planea.jpg.asset.json";
import libretaStitchAzul from "@/assets/libreta-stitch-azul.jpg.asset.json";
import libretaMisIdeas from "@/assets/libreta-mis-ideas.jpg.asset.json";
import libretaNotasPortada from "@/assets/libreta-notas-portada.jpg.asset.json";
import libretaNotasInterior from "@/assets/libreta-notas-interior.jpg.asset.json";
import libretaCitas from "@/assets/libreta-citas.jpg.asset.json";
import calendario2026Portada from "@/assets/calendario-2026-portada.jpg.asset.json";
import calendario2026Enero from "@/assets/calendario-2026-enero.jpg.asset.json";
import libretaOhanaStitch from "@/assets/libreta-ohana-stitch.jpg.asset.json";
import libretaVideoDemo from "@/assets/libreta-video-demo.mp4.asset.json";
import libretaGrandesPlanes from "@/assets/libreta-grandes-planes.jpg.asset.json";
import libretaMomentos from "@/assets/libreta-momentos.jpg.asset.json";
import libretaMomentosDemo from "@/assets/libreta-momentos-demo.mp4.asset.json";
import libretaMemorias from "@/assets/libreta-memorias.jpg.asset.json";
import libretaMemoriasDemo from "@/assets/libreta-memorias-demo.mp4.asset.json";
import libretaVivimosFeDemo from "@/assets/libreta-vivimos-fe-demo.mp4.asset.json";
import libretaDreamsDemo from "@/assets/libreta-dreams-demo.mp4.asset.json";
import idealoLogoColor from "@/assets/idealo-logo-color.png.asset.json";

export type ProjectType =
  | "Stickers"
  | "Banderines"
  | "Iron-ons"
  | "PVC"
  | "Impresos"
  | "Libretas"
  | "Rotulación"
  | "Regalos"
  | "Servicios";

export type Project = {
  slug: string;
  title: string;
  tag: string;
  subtitle: string;
  type: ProjectType;
  image?: string;
  gradient?: string;
  bg?: string;
  fit?: "cover" | "contain";
  /** Optional watermark/logo overlaid on the card image (top-left). */
  watermark?: string;
  /** Optional secondary image (e.g. interior view of a notebook). */
  extraImages?: string[];
  /** Optional demo video (muted, autoplays on click on the detail page). */
  video?: string;
  /** Long-form description shown on the detail page. */
  description?: string;
  /** Bullet highlights shown on the detail page. */
  highlights?: string[];
};

export const slugify = (s: string) =>
  s
    .toLowerCase()
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, "")
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/(^-|-$)/g, "");

const raw: Omit<Project, "slug">[] = [
  { title: "Termo Térmico Skinny para Mamá", tag: "Regalos & Mamá", type: "Regalos", subtitle: "Termo skinny sublimado full color · diseño 'Mereces lo que Sueñas' y frases para Mamá", image: termoMamaMariposas.url, bg: "#fce7f3", fit: "contain", description: "Termo térmico skinny sublimado full color con diseño 100% personalizado. Ideal para Día de la Madre, cumpleaños y regalos únicos. Diseños disponibles: 'Mereces lo que Sueñas' con mariposas y 'Mamá Eres' con frases motivacionales. Cualquier diseño, foto o frase que desees.", highlights: ["Sublimación full color 360°", "Diseño 100% personalizado", "Ideal para Día de la Madre", "Cualquier foto, nombre o frase"] },
  { title: "Fotos tipo cristal", tag: "Regalos & Recuerdos", type: "Regalos", subtitle: "Fotos impresas tipo cristal con el diseño y tamaño que prefieras · ideal para aniversarios y bodas", image: fotosCristal.url, bg: "#e8ede8", fit: "contain", description: "Fotos impresas tipo cristal, acabado premium tipo periódico o collage personalizado. Diseño 100% a la medida con las fotos, textos y tamaño que prefieras. Perfectas para aniversarios, bodas, cumpleaños y regalos únicos.", highlights: ["Acabado tipo cristal premium", "El diseño y tamaño que prefieras", "Ideal para aniversarios y bodas", "Regalo único y personalizado"] },
  { title: "Snacks Personalizados", tag: "Branding & Empaques", type: "Regalos", subtitle: "Empaques de snacks personalizados con tu marca · ideal para eventos y regalos corporativos", image: snacksPersonalizados.url, bg: "#ffffff", fit: "cover", description: "Snacks personalizados con empaque impreso a la medida de tu marca o evento. Ideales para bodas, cumpleaños, activaciones, regalos corporativos y detalles para invitados. Cualquier diseño, sabor y cantidad.", highlights: ["Empaque 100% personalizado", "Ideal para eventos y regalos corporativos", "Cualquier diseño y cantidad", "Detalle único para invitados"] },
  { title: "Stickers troquelados en varios tamaños", tag: "Personalizados", type: "Stickers", subtitle: "Desde 1×1 hasta 3.5×3.5 pulgadas · cualquier forma, diseño y tamaño que desees", image: stickersTamanos.url, bg: "#ffffff", fit: "contain", description: "Stickers troquelados disponibles en múltiples tamaños: 1×1, 2×2, 2.5×2.5, 3×3 y 3.5×3.5 pulgadas. Se pueden realizar de la forma, diseño y tamaño que desees. Ideales para branding, empaques, eventos y regalos.", highlights: ["Tamaños desde 1×1 hasta 3.5×3.5 pulgadas", "Cualquier forma y diseño", "Vinil premium impermeable", "Impresión full color HD"] },
  { title: "Impresión Láser · Invitaciones Capy Birthday", tag: "Impresión & Papelería", type: "Impresos", subtitle: "Invitaciones full color en Opalina, Lino, Papel Photo, Bond y muchos más", image: impresionLaserCapy.url, bg: "#1a1533", fit: "contain", description: "Impresión láser full color para invitaciones, tarjetas y papelería de eventos. Disponible en varios tipos de papel: Opalina, Lino, Papel Photo, Bond y muchos más. Diseño 100% personalizado para cumpleaños, bodas, XV años y eventos corporativos.", highlights: ["Impresión láser full color", "Papeles: Opalina, Lino, Photo, Bond y más", "Diseño 100% personalizado", "Ideal para invitaciones y papelería de eventos"] },
  { title: "Sticker Troquelado · Brioche Bakery", tag: "Branding & Panadería", type: "Stickers", subtitle: "Stickers troquelados a la forma del logo · vinil premium para empaques", image: stickerTroqueladoBrioche.url, bg: "#2f3f2b", fit: "contain", description: "Stickers troquelados a la forma exacta del logo, perfectos para etiquetar empaques de panadería, cafetería y repostería. Se pueden realizar de cualquier forma, tamaño y acabado (mate, brillante o transparente).", highlights: ["Corte troquelado a la forma del logo", "Vinil premium resistente", "Ideal para empaques y branding", "Cualquier forma, tamaño y acabado"] },
  { title: "Audio Guestbook", tag: "Servicio para Eventos", type: "Servicios", subtitle: "Teléfono vintage para grabar mensajes de voz de tus invitados · recuerdo único", image: audioGuestbook.url, bg: "#1e6fa8", fit: "contain", description: "Servicio de Audio Guestbook: un teléfono vintage donde tus invitados dejan un mensaje de voz especial para el festejado. Incluye rótulo personalizado con nombre y fecha. Recibí todos los audios recopilados después del evento como un recuerdo inolvidable.", highlights: ["Teléfono vintage funcional", "Rótulo personalizado incluido", "Audios entregados después del evento", "Ideal para bodas, cumpleaños y XV"] },
  { title: "Etiquetas para botellas de guifiti", tag: "Eventos & Bebidas", type: "Stickers", subtitle: "Stickers personalizados para botellas de guifiti · cualquier forma, diseño y tamaño", image: etiquetasGuifitiBotellas.url, bg: "#0f2b4a", fit: "contain", description: "Etiquetas adhesivas personalizadas para botellas de guifiti, licores artesanales y bebidas típicas. Se pueden realizar de la forma, diseño y tamaño que desees, con acabado resistente a la humedad ideal para presentación de producto y regalos.", highlights: ["Forma, diseño y tamaño a medida", "Acabado resistente a la humedad", "Ideal para guifiti y licores artesanales", "Presentación premium para tu marca"] },
  { title: "PVC de bienvenida para cumpleaños", tag: "Eventos & Cumpleaños", type: "PVC", subtitle: "Sticker + PVC de bienvenida personalizado con el nombre y diseño del festejado", image: pvcBienvenidaJessie.url, bg: "#2a2350", fit: "contain", description: "PVC de bienvenida con sticker impreso personalizado para recibir a tus invitados. Se puede personalizar con el diseño, colores, frases y tamaño que desees. Perfecto para cumpleaños, XV años, bodas y todo tipo de eventos.", highlights: ["Diseño 100% personalizado", "Tamaño a medida", "Impresión en alta calidad sobre PVC", "Ideal para entrada de eventos"] },
  { title: "Cuadros en canvas", tag: "Hogar & Decoración", type: "Impresos", subtitle: "Tú escoges la foto y el tamaño · impresión en canvas para decorar tu hogar", image: cuadrosCanvas.url, bg: "#f2ecec", fit: "contain", description: "Cuadros impresos en canvas con la foto que elijas, en el tamaño y formato que prefieras. Perfectos para decorar sala, dormitorio u oficina, y también como regalo para aniversarios, cumpleaños y ocasiones especiales.", highlights: ["Impresión en canvas de alta calidad", "Tamaños y formatos personalizables (1 o varias piezas)", "Ideal para decoración y regalos", "Listo para colgar"] },
  { title: "Cajitas de candy con sticker personalizado", tag: "Eventos & Detalles", type: "Stickers", subtitle: "Cajitas acrílicas con sticker personalizado · ideal para recuerdos de eventos y bodas", image: cajitasCandySticker.url, bg: "#f5f0e8", fit: "contain", description: "Cajitas acrílicas rellenas de candy con sticker personalizado en la tapa. Se realizan de la forma, diseño y tamaño que desees. Perfectas como recuerdos de bodas, cumpleaños, baby showers y eventos corporativos.", highlights: ["Sticker 100% personalizado", "Cualquier forma y tamaño", "Detalle listo para regalar", "Ideal para eventos y bodas"] },
  { title: "Abanicos de madera con grabado láser", tag: "Eventos & Bodas", type: "Regalos", subtitle: "Abanicos personalizados para invitados con grabado láser · ideal para bodas y cumpleaños", image: abanicoLaser.url, bg: "#f0eae4", fit: "contain", description: "Abanicos de madera personalizados con grabado láser, perfectos como detalle para invitados en bodas, quinceaños y cumpleaños. Grabado permanente con el nombre, fecha o mensaje del evento.", highlights: ["Grabado láser permanente", "Nombre o fecha personalizada", "Ideal para bodas y eventos", "Detalle elegante para invitados"] },
  { title: "Bolsos sublimados", tag: "Regalos & Mamá", type: "Regalos", subtitle: "Bolsos de tela con sublimación full color · diseño 100% personalizado", image: bolsosSublimados.url, bg: "#c026d3", fit: "contain", description: "Bolsos de tela sublimados con diseño 100% personalizado. Sublimación full color de borde a borde, ideal para Día de la Madre, cumpleaños, bodas y regalos corporativos.", highlights: ["Sublimación full color", "Diseño 100% personalizado", "Ideal para Día de la Madre", "Perfectos para regalos y branding"] },
  { title: "Bolsos de yute personalizados para Mamá", tag: "Regalos & Mamá", type: "Regalos", subtitle: "Bolsos de yute con nombre en vinil textil · incluye pompones decorativos", image: bolsosMama.url, bg: "#fce7f3", fit: "contain", description: "Bolsos de yute personalizados con el nombre en vinil textil de alta calidad. Incluyen pompones decorativos. Regalo ideal para Día de la Madre, bodas, damas de honor y detalles corporativos.", highlights: ["Yute natural resistente", "Nombre en vinil textil", "Pompones decorativos incluidos", "Cualquier nombre o frase"] },
  { title: "Termos personalizados con grabado láser", tag: "Regalos", type: "Regalos", subtitle: "Termos Stanley y similares con grabado láser permanente · nombre, frase o logo", image: termoStanley.url, bg: "#a7c4a0", fit: "contain", description: "Termos tipo Stanley y similares personalizados con grabado láser permanente. Perfectos para regalos corporativos, cumpleaños, aniversarios y detalles únicos. El grabado no se borra ni se despinta.", highlights: ["Grabado láser permanente", "Nombre, frase o logo", "Varios colores disponibles", "Ideal para regalos y corporativo"] },
  { title: "Esferas navideñas personalizadas", tag: "Navidad", type: "Regalos", subtitle: "Esferas transparentes con foto o vinil · Merry Christmas y foto preferida", image: esferasNavidenas.url, bg: "#f5f5f5", fit: "contain", description: "Esferas navideñas transparentes personalizadas con tu foto preferida o vinil decorativo (Merry Christmas, nombres, fechas). Detalle perfecto para el árbol de navidad, regalos corporativos y recuerdos familiares.", highlights: ["Esfera transparente premium", "Foto o vinil personalizado", "Lazo rojo decorativo", "Regalo ideal de Navidad"] },
  { title: "Marcos personalizados con foto", tag: "Regalos & Hogar", type: "Regalos", subtitle: "Marcos con foto impresa personalizada · ideal para mascotas, familia y parejas", image: marcosPersonalizados.url, bg: "#7f1d1d", fit: "contain", description: "Marcos personalizados con foto impresa en alta calidad. Diseños únicos para mascotas, familia, parejas y momentos especiales. Solo mándanos la foto y nosotros hacemos el diseño.", highlights: ["Impresión fotográfica HD", "Diseño personalizado incluido", "Marco de calidad premium", "Ideal para mascotas y familia"] },
  { title: "Fotos personalizadas tipo Polaroid", tag: "Regalos & Recuerdos", type: "Regalos", subtitle: "Sets de fotos tipo Polaroid con tus momentos favoritos · Moments 2021, 2022...", image: fotosPersonalizadas.url, bg: "#7f1d1d", fit: "contain", description: "Sets de fotos personalizadas estilo Polaroid con tus momentos favoritos. Perfectas para regalar, decorar el cuarto o crear un mural de recuerdos. Solo mándanos tus fotos.", highlights: ["Estilo Polaroid vintage", "Cualquier cantidad de fotos", "Impresión fotográfica HD", "Ideal para regalos y decoración"] },
  { title: "Impresión en cartoncillo láser", tag: "Impresos Personalizados", type: "Impresos", subtitle: "Se pueden realizar de la figura, diseño y tamaño que desees · ideal para envoltorios y detalles", image: impresionCartoncillo.url, bg: "#0a0a0a", fit: "contain", description: "Impresión láser en cartoncillo para envoltorios personalizados, etiquetas decorativas y detalles únicos. Cualquier figura, diseño y tamaño. Ideal para bebidas, regalos y eventos temáticos.", highlights: ["Cualquier figura y tamaño", "Impresión láser de alta calidad", "Diseño 100% personalizado", "Ideal para envoltorios y detalles"] },
  { title: "Grabado láser en coco", tag: "Eventos & Regalos", type: "Regalos", subtitle: "Grabado láser de alta calidad en superficies planas · perfecto para cumpleaños y eventos tropicales", image: grabadoLaserCoco.url, bg: "#0a0a0a", fit: "contain", description: "Grabado láser de alta calidad en cocos y otras superficies planas. Ideal para cumpleaños, bodas tropicales, hoteles y eventos que buscan un detalle único con el nombre del festejado o mensaje personalizado.", highlights: ["Grabado láser permanente", "Superficies planas de todo tipo", "Nombre o mensaje personalizado", "Perfecto para eventos"] },
  { title: "Etiquetas con foil metálico", tag: "Etiquetas Premium", type: "Stickers", subtitle: "Etiquetas con foil dorado, plateado o holográfico · ideal para joyería, tarjetas y productos premium", image: etiquetasFoil.url, bg: "#f5f5f5", fit: "contain", description: "Etiquetas premium con foil metálico dorado, plateado o holográfico. Acabado de lujo ideal para joyería, tarjetas de marca, cosméticos y productos artesanales que quieren destacar.", highlights: ["Foil dorado, plateado u holográfico", "Acabado premium", "Cualquier forma y tamaño", "Ideal para joyería y branding"] },
  { title: "Menús para restaurantes", tag: "Restaurantes", type: "Impresos", subtitle: "Impresión doble lado · espiral de metal · laminado", image: menus.url, bg: "#d9d9d9", description: "Menús diseñados y producidos para durar todo el servicio. Impresión doble lado en papel grueso, laminado brillante o mate y encuadernado con espiral metálica. Ideales para restaurantes, cafeterías y bares que renuevan carta constantemente.", highlights: ["Impresión doble lado full color", "Laminado brillante o mate", "Espiral metálica resistente", "Cualquier tamaño y cantidad"] },
  { title: "Stickers de marca", tag: "Emprendedores", type: "Stickers", subtitle: "Impresión de alta calidad · material impermeable", image: stickersMarca.url, bg: "#1a1410", description: "Stickers para empaques, empaques kraft, cajas o bolsas. Material vinil impermeable con colores vivos y adhesivo permanente que aguanta manipulación y clima.", highlights: ["Vinil impermeable", "Colores vivos full color", "Corte por contorno", "Cualquier forma y tamaño"] },
  { title: "Carpetas corporativas", tag: "Corporativo", type: "Impresos", subtitle: "Cartón laminado · doble compartimiento", image: carpetas.url, bg: "#ffffff", description: "Carpetas presentadoras en cartón laminado con doble compartimiento interno para propuestas, contratos y material corporativo. Personalizadas con tu logo, colores y branding completo.", highlights: ["Cartón grueso laminado", "Doble compartimiento", "Troquelado profesional", "Diseño 100% personalizado"] },
  { title: "Stickers troquelados", tag: "Personalizados", type: "Stickers", subtitle: "Cualquier forma, diseño y tamaño", image: troquelados.url, bg: "#fafafa", description: "Stickers troquelados a la forma exacta de tu diseño. Perfectos para branding, packaging, merchandising y regalos. Producción en cantidades pequeñas y grandes.", highlights: ["Troquelado kiss-cut o die-cut", "Vinil premium impermeable", "Colores full HD", "Desde 1 unidad"] },
  { title: "Banners Roll Up", tag: "Publicidad", type: "Banderines", subtitle: "33.5 × 78.7 pulgadas · incluye araña y estuche", image: banner.url, bg: "#ffffff", fit: "contain", description: "Roll up publicitario listo para usar en ferias, stands y eventos corporativos. Incluye estructura araña, base con contrapeso y estuche para transporte.", highlights: ["33.5 × 78.7 pulgadas", "Estructura araña incluida", "Estuche de transporte", "Fácil armado en 60 segundos"] },
  { title: "Microperforado", tag: "Fachadas", type: "Rotulación", subtitle: "Vinil para vidrieras y locales comerciales", image: microperforado.url, bg: "#5b6672", description: "Vinil microperforado ideal para vidrieras, ventanas de locales y vehículos. Se ve tu diseño por fuera y mantiene la visibilidad desde adentro.", highlights: ["Visibilidad desde el interior", "Impresión full color exterior", "Instalación profesional", "Resistente a la intemperie"] },
  { title: "Rotulación industrial", tag: "Señalética", type: "Rotulación", subtitle: "Señales de seguridad y rotulación empresarial", image: rotulacion.url, bg: "#1f4a7a", description: "Señales de seguridad, informativas y rotulación empresarial para plantas industriales, oficinas y espacios comerciales. Cumplimos con normativas locales.", highlights: ["Materiales industriales", "Cumple normativa", "Instalación incluida", "Cualquier tamaño"] },
  { title: "Tarjetas de presentación profesionales", tag: "Branding", type: "Impresos", subtitle: "Papel premium · acabados brillantes o mate", image: tarjetas.url, bg: "#eaf4fb", description: "Tarjetas de presentación en papel premium con acabados brillante, mate o soft touch. Desde 100 hasta 5,000 unidades con tu diseño personalizado.", highlights: ["Papel 300g premium", "Acabado brillante / mate / soft touch", "Doble lado full color", "Diseño incluido"] },
  { title: "Rótulos de bienvenida escolares", tag: "Escuelas", type: "PVC", subtitle: "Diseño personalizado · impresión de alta calidad · cualquier tamaño", image: backToSchool.url, bg: "#0ea5e9", fit: "contain", description: "Rótulos de bienvenida en PVC para el regreso a clases. Diseño personalizado con el nombre del alumno o de la escuela, impresión de alta calidad y cualquier tamaño.", highlights: ["PVC de 3, 5 y 10 mm", "Impresión full color HD", "Cualquier tamaño y forma", "Diseño 100% personalizado"] },
  { title: "Stand para fotos", tag: "Eventos", type: "PVC", subtitle: "Backdrop temático en PVC con troquelado y sticker de alta calidad", image: standFotos.url, bg: "#0f172a", fit: "contain", description: "Backdrops temáticos para fotos en eventos, cumpleaños y activaciones de marca. PVC troquelado con sticker de alta calidad para un acabado premium.", highlights: ["PVC rígido troquelado", "Sticker HD aplicado", "Cualquier tema o personaje", "Fácil instalación"] },
  { title: "Espejo con stickers en vinil", tag: "Restaurantes & Bares", type: "Stickers", subtitle: "Stickers en vinil aplicados sobre espejo para ambientar tu local", image: espejoStickers.url, bg: "#1a0b2e", description: "Stickers en vinil aplicados sobre espejo para bares, restaurantes y locales que quieren un toque decorativo con impacto visual.", highlights: ["Vinil premium", "Instalación profesional", "Cualquier diseño y tamaño", "Removible sin dañar"] },
  { title: "Menús en sticker + PVC", tag: "Restaurantes", type: "PVC", subtitle: "Menú rígido resistente al agua · diseño 100% personalizado", image: menuPvc.url, bg: "#111827", description: "Menús rígidos hechos con sticker sobre PVC. Resistentes al agua, aceite y manipulación diaria. Diseño 100% personalizado.", highlights: ["PVC rígido resistente", "Sticker HD aplicado", "Resistente al agua y aceite", "Cualquier tamaño"] },
  { title: "Figuras de PVC + sticker", tag: "Publicidad", type: "PVC", subtitle: "Displays troquelados en PVC ideales para promoción y marca", image: figuraPvc.url, bg: "#1f2937", fit: "contain", description: "Displays troquelados en PVC con sticker aplicado. Ideales para promociones, punto de venta y activaciones de marca.", highlights: ["Troquelado a la forma", "PVC de 3 o 5 mm", "Sticker HD", "Cualquier tamaño"] },
  { title: "PVC de bienvenida para eventos", tag: "Eventos", type: "PVC", subtitle: "Cartel personalizado con nombre · diseño premium para cumpleaños y celebraciones", image: pvcGaby.url, bg: "#0a0a0a", fit: "contain", description: "Carteles de bienvenida en PVC personalizados con el nombre del festejado. Diseño premium para cumpleaños, bodas, baby showers y toda clase de celebraciones.", highlights: ["Diseño 100% personalizado", "PVC de 5 o 10 mm", "Troquelado profesional", "Cualquier tamaño"] },
  { title: "Figuras troqueladas Sticker + PVC", tag: "Publicidad", type: "PVC", subtitle: "Disponibles en cualquier tamaño y personajes · ideal para promociones y eventos", image: figurasMundial.url, bg: "#e5e5e5", fit: "contain", description: "Figuras troqueladas de personajes, mascotas o productos hechas con sticker + PVC. Ideales para promociones, eventos y punto de venta.", highlights: ["Cualquier tamaño", "Cualquier personaje", "PVC rígido troquelado", "Base opcional para exhibición"] },
  { title: "Banderines publicitarios", tag: "Publicidad", type: "Banderines", subtitle: "Disponibles de 3 y 5 metros · material impermeable · incluye base y contrapeso", image: banderines.url, bg: "#0a0a0a", fit: "contain", description: "Banderines tipo pluma para exteriores. Material impermeable resistente al sol y la lluvia. Incluye asta, base y contrapeso.", highlights: ["3 y 5 metros de alto", "Material impermeable", "Incluye base con contrapeso", "Fácil transporte"] },
  { title: "Foto Álbum", tag: "Regalos", type: "Regalos", subtitle: "Álbum personalizado con el nombre y diseño que quieras · ideal para regalos, aniversarios y ocasiones especiales", image: albumMama2.url, bg: "#ec4899", fit: "contain", description: "Foto álbumes personalizados con nombre, portada temática y las fotos que quieras. Perfectos para regalos, aniversarios, día de la madre, cumpleaños y ocasiones especiales.", highlights: ["Portada personalizada", "Impresión fotográfica HD", "Varios tamaños y páginas", "Solo mándanos tus fotos"] },
  { title: "Banner cruza calle", tag: "Publicidad", type: "Banderines", subtitle: "540 × 58 pulgadas · impresión de alta calidad · material resistente · incluye instalación", image: bannerCruzacalle.url, bg: "#0a0a0a", fit: "contain", description: "Banners cruza calle de gran formato para publicidad masiva. Material resistente para exteriores e instalación incluida.", highlights: ["540 × 58 pulgadas", "Material resistente a la intemperie", "Impresión HD full color", "Instalación incluida"] },
  { title: "Variedad de banners", tag: "Publicidad", type: "Banderines", subtitle: "Banner cruza calle, mini banner de mesa, roll up y banner araña · cualquier tamaño", image: variedadBanners.url, bg: "#ffffff", description: "Todos los tipos de banners bajo un mismo techo: cruza calle, mini banner de mesa, roll up, araña y banderines tipo pluma. Cualquier tamaño y cantidad.", highlights: ["Roll up, araña y cruza calle", "Mini banner de mesa", "Cualquier tamaño", "Producción rápida"] },
  { title: "Grabado láser para Papá", tag: "Regalos", type: "Regalos", subtitle: "Billeteras, termos y tablas de cortar con grabado láser personalizado · regalo perfecto para Papá", image: grabadoPapa.url, bg: "#0a0a0a", description: "Regalos para Papá con grabado láser: billeteras de cuero, termos metálicos y tablas de cortar personalizadas con nombre, foto o dedicatoria.", highlights: ["Grabado láser permanente", "Cuero, metal y madera", "Foto, texto o logo", "Regalo listo para entregar"] },
  { title: "Camisetas personalizadas para Papá", tag: "Regalos", type: "Regalos", subtitle: "Camisetas con foto, nombre y diseño 100% personalizado · solo mándanos las fotos de Papá", image: camisetasPapa.url, bg: "#0a0a0a", description: "Camisetas full color con foto, nombre y diseño 100% personalizado. Solo mándanos las fotos de Papá y nosotros hacemos el diseño.", highlights: ["Sublimación full color", "Diseño incluido", "Todas las tallas", "Solo mándanos la foto"] },
  { title: "Botellas personalizadas", tag: "Regalos", type: "Regalos", subtitle: "Botellas con nombre o foto · etiquetas premium · ideal para regalos y ocasiones especiales", image: botellasPersonalizadas.url, bg: "#0a0a0a", fit: "contain", description: "Botellas de vidrio o metal personalizadas con nombre, foto o etiqueta premium. Ideales para regalos, brindis y ocasiones especiales.", highlights: ["Etiqueta premium en vinil", "Vidrio o metal", "Cualquier diseño", "Perfecto para regalar"] },
  { title: "Etiquetas para botellas en vinil", tag: "Regalos", type: "Stickers", subtitle: "Etiqueta completa en sticker vinil · personaliza cerveza o bebidas con nombre y diseño", image: etiquetasBotellas.url, bg: "#f5f5f5", fit: "contain", description: "Etiquetas completas en sticker vinil impermeable para personalizar cervezas, vinos y bebidas artesanales. Diseño 100% personalizado.", highlights: ["Vinil impermeable", "Cualquier tamaño de botella", "Corte por contorno", "Full color HD"] },
  { title: "Marcos con fotos impresas", tag: "Regalos", type: "Regalos", subtitle: "Set de marcos con tus fotos impresas · solo mándanos las fotos · regalo perfecto para toda ocasión", image: marcosFotos.url, bg: "#e5e5e5", fit: "contain", description: "Sets de marcos con fotos impresas de alta calidad. Perfectos para regalar en cualquier ocasión: cumpleaños, aniversarios, día de la madre o del padre.", highlights: ["Impresión fotográfica HD", "Marcos incluidos", "Solo mándanos tus fotos", "Cualquier cantidad"] },
  { title: "Cadenas con grabado láser", tag: "Regalos", type: "Regalos", subtitle: "Dijes personalizados con foto o nombre · grabado láser en acero · solo mándanos tu foto", image: cadenasGrabado.url, bg: "#ffffff", fit: "contain", description: "Dijes y cadenas de acero con grabado láser de foto, nombre o texto. Grabado permanente que no se borra. Regalo ideal para parejas, mamás y amigos.", highlights: ["Grabado láser permanente", "Acero inoxidable", "Foto o texto", "Estuche incluido"] },
  { title: "Boxers personalizados para San Valentín", tag: "Regalos", type: "Regalos", subtitle: "Sublimación full color · diseños divertidos y románticos · solo mándanos tu foto o idea", image: boxersPersonalizados.url, bg: "#ffffff", fit: "contain", description: "Boxers personalizados con sublimación full color. Diseños divertidos y románticos para San Valentín, aniversarios o solo para reír.", highlights: ["Sublimación full color", "Todas las tallas", "Solo mándanos la idea", "Empaque de regalo"] },
  { title: "Calsetas personalizadas con foto", tag: "Regalos", type: "Regalos", subtitle: "Sublimación full color · caras, nombres y corazones · solo mándanos tu foto", image: calsetasPersonalizadas.url, bg: "#ffffff", fit: "contain", description: "Calcetas con foto, nombre o diseño personalizado. Sublimación full color que no se despinta. Regalo original para parejas, amigos y familia.", highlights: ["Sublimación full color", "Todas las tallas", "Solo mándanos la foto", "Diseño incluido"] },
  { title: "Retrateras con tu foto impresa", tag: "Regalos", type: "Regalos", subtitle: "Marcos de madera, metal y decorativos · impresión fotográfica de alta calidad · solo mándanos tu foto", image: retrateras.url, bg: "#ffffff", fit: "contain", description: "Retrateras con tu foto impresa en alta calidad. Marcos de madera, metal y decorativos para regalar o decorar tu espacio.", highlights: ["Impresión fotográfica HD", "Marcos de madera o metal", "Varios tamaños", "Solo mándanos la foto"] },
  { title: "Rompecabezas personalizados", tag: "Regalos", type: "Regalos", subtitle: "Puzzle con tu foto favorita · varios tamaños y piezas · solo mándanos tu foto", image: rompecabezas.url, bg: "#ffffff", fit: "contain", description: "Rompecabezas personalizados con tu foto favorita. Varios tamaños y cantidades de piezas. Incluye caja de regalo.", highlights: ["Foto full HD", "Varios tamaños y piezas", "Caja de regalo incluida", "Solo mándanos la foto"] },
  { title: "Impresión de fotos tipo Polaroid", tag: "Regalos", type: "Impresos", subtitle: "Fotos estilo Polaroid con acabado premium · ideal para regalos, decoración y recuerdos", image: polaroid.url, bg: "#f5f5f5", fit: "contain", description: "Impresión de fotos estilo Polaroid con acabado premium. Perfectas para regalar, decorar tu cuarto o armar álbumes de recuerdos.", highlights: ["Acabado premium", "Cualquier cantidad", "Papel fotográfico", "Solo mándanos las fotos"] },
  { title: "Rollos para facturación", tag: "Negocios", type: "Impresos", subtitle: "Rollos térmicos y químicos para impresoras de facturación · excelente precio y calidad", image: rollosFacturacion.url, bg: "#ffffff", fit: "contain", description: "Rollos térmicos y químicos para impresoras de facturación. Compatible con las principales marcas. Excelente precio para negocios que facturan mucho.", highlights: ["Térmico y químico", "Todos los tamaños", "Compatible con toda impresora", "Descuentos por cantidad"] },
  { title: "Sublimación en tazas y termos", tag: "Regalos & Branding", type: "Regalos", subtitle: "Impresión duradera full color · tazas cerámicas, termos y botellas · personaliza con foto, logo o diseño", image: sublimacion.url, bg: "#f5efe7", fit: "contain", description: "Sublimación full color en tazas cerámicas, termos metálicos y botellas. Impresión duradera que resiste el lavavajillas. Perfecto para regalos y branding corporativo.", highlights: ["Impresión duradera", "Full color HD", "Foto, logo o diseño", "Apta para lavavajillas"] },
  { title: "Personaliza tus empaques", tag: "Empaques & Etiquetas", type: "Impresos", subtitle: "Tarjetas cliente frecuente · etiquetas para ropa y joyería · tarjetas de presentación con tu logo, foto y colores", image: empaques.url, bg: "#ffffff", fit: "contain", description: "Kit completo para personalizar tus empaques: tarjetas de cliente frecuente, hang tags para ropa y joyería, tarjetas de presentación y etiquetas con tu logo, foto y colores.", highlights: ["Tarjetas cliente frecuente", "Hang tags para ropa y joyería", "Tarjetas de presentación", "Diseño incluido"] },
  { title: "Stickers para empaques", tag: "Empaques & Branding", type: "Stickers", subtitle: "Stickers troquelados para bolsas, vasos, cajas y contenedores kraft · cualquier forma, diseño y tamaño", image: stickersEmpaques.url, bg: "#ffffff", fit: "contain", description: "Stickers troquelados para bolsas kraft, vasos, cajas y contenedores. Perfectos para marcar empaques de comida, delivery y ecommerce.", highlights: ["Vinil impermeable", "Troquelado a la forma", "Cualquier tamaño", "Descuentos por cantidad"] },
  { title: "Etiquetas para bebidas", tag: "Etiquetas", type: "Stickers", subtitle: "Impresión de alta calidad · material impermeable · cualquier tamaño de botella · personalízalas con tu logo, foto y colores", image: etiquetasBebidas.url, bg: "#ffffff", fit: "contain", description: "Etiquetas impermeables para botellas de bebidas: cerveza artesanal, vinos, jugos, kombucha y más. Impresión HD full color con tu logo y branding.", highlights: ["Vinil impermeable", "Cualquier tamaño de botella", "Corte por contorno", "Impresión HD"] },
  { title: "Etiquetas para tus productos", tag: "Etiquetas", type: "Stickers", subtitle: "Troqueladas a la forma de tu preferencia · perfectas para salsas, bebidas y productos artesanales", image: etiquetasGuifity.url, bg: "#ffffff", fit: "contain", description: "Etiquetas troqueladas a la forma que quieras para salsas, mermeladas, cosméticos y productos artesanales. Perfectas para emprendedores.", highlights: ["Troquelado personalizado", "Vinil impermeable", "Cualquier diseño", "Desde cantidades pequeñas"] },
  { title: "Etiquetas para cumpleaños", tag: "Eventos", type: "Stickers", subtitle: "Etiquetas personalizadas para botellas de agua · monograma, nombre o versículo · perfectas para cumpleaños y celebraciones", image: etiquetasCumple.url, bg: "#ffffff", fit: "contain", description: "Etiquetas personalizadas para botellas de agua en cumpleaños, baby showers, bodas y celebraciones. Monograma, nombre del festejado o versículo bíblico.", highlights: ["Cualquier tamaño de botella", "Monograma o nombre", "Vinil impermeable", "Desde 50 unidades"] },
  { title: "Servicio de cámara 360°", tag: "Eventos", type: "Servicios", subtitle: "Cámara 360° con plataforma iluminada · ideal para bodas, cumpleaños y eventos corporativos · videos instantáneos para tus invitados", image: servicio360.url, bg: "#0a0a0a", fit: "contain", description: "Servicio de cámara 360° con plataforma iluminada para eventos. Tus invitados suben, la cámara gira y reciben un video instantáneo por WhatsApp con la música y branding que elijas.", highlights: ["Plataforma iluminada con luces LED", "Videos instantáneos por WhatsApp", "Música y overlays personalizados", "Operador incluido"] },
  { title: "Impresión en jarra", tag: "Bares & Eventos", type: "Regalos", subtitle: "Jarras personalizadas con tu logo, nombre o foto · también etiquetas para botellas · perfectas para bares, cervezas artesanales y regalos", image: impresionJarra.url, bg: "#ffffff", fit: "contain", description: "Jarras de cerveza personalizadas con tu logo, nombre o foto. Impresión full color duradera. Perfectas para bares, cervezas artesanales, souvenirs y regalos originales.", highlights: ["Impresión full color duradera", "Cualquier logo o foto", "También etiquetas de botella", "Descuentos por cantidad"] },
  { title: "Kit de regalos corporativos", tag: "Corporativo", type: "Regalos", subtitle: "Libretas, tazas, termos, stickers, llaveros, lanyards y más · armado a tu gusto con tu logo, colores e identidad corporativa", image: regalosCorporativos.url, bg: "#f2f2f2", fit: "contain", description: "Kits de regalos corporativos totalmente personalizados con tu logo, colores e identidad de marca. Elegí los productos que querés incluir y nosotros armamos la caja lista para entregar a clientes, colaboradores o aliados estratégicos.", highlights: ["Libretas, cuadernos y calendarios", "Tazas, vasos y termos", "Stickers, llaveros y lanyards", "Plumas, lápices y mousepads", "Armado y empacado incluido"] },
  { title: "Tazas sublimadas personalizadas", tag: "Regalos & Branding", type: "Regalos", subtitle: "Personalizalas con tu logo, nombre o foto · sublimación full color · consulta por la variedad de tazas disponibles", image: tazasSublimadas.url, bg: "#5cc7e6", fit: "contain", description: "Tazas sublimadas personalizadas con tu logo, nombre o foto favorita. Sublimación full color de alta durabilidad, apta para lavavajillas. Variedad de tazas cerámicas, mágicas y de color disponibles.", highlights: ["Sublimación full color HD", "Apta para lavavajillas", "Foto, logo o diseño personalizado", "Variedad de modelos disponibles"] },
  { title: "Calendarios corporativos", tag: "Corporativo", type: "Impresos", subtitle: "Calendarios de escritorio y de pared · personalizalos con tu logo, nombre y/o foto · ideales para regalos corporativos de fin de año", image: calendariosCorporativos.url, bg: "#ececec", fit: "contain", description: "Calendarios corporativos personalizados con tu logo, nombre y/o foto. Disponibles en versión de escritorio y de pared. Ideales como regalo de fin de año para clientes, colaboradores y aliados estratégicos.", highlights: ["Calendarios de escritorio y de pared", "Personalización con logo, nombre y foto", "Impresión full color HD", "Descuentos por cantidad"] },
  { title: "Combos corporativos con tu marca", tag: "Corporativo", type: "Regalos", subtitle: "Mochila, libreta, calendario, taza, termo, mousepad y lanyard · personalizados con tu logo, nombre o foto · precio especial en pedidos grandes", image: combosCorporativos.url, bg: "#a5d8ec", fit: "contain", description: "Combos corporativos armados con tu marca: mochila, libreta, calendario, taza, termo, mousepad y lanyard personalizados con tu logo, nombre o foto. Precio especial en pedidos grandes para clientes, colaboradores y eventos.", highlights: ["Mochila, taza, termo y libreta", "Calendario, mousepad y lanyard", "Personalización con logo, nombre o foto", "Precio especial en pedidos grandes"] },
  { title: "Camisetas patrióticas Honduras", tag: "Fiestas Patrias", type: "Iron-ons", subtitle: "Camisetas blancas y negras con diseños hondureños · guacamaya, tortuga y palmeras · personalizables con tu nombre o marca", image: camisetasHonduras.url, bg: "#ffffff", fit: "contain", description: "Camisetas patrióticas con diseños hondureños: guacamaya, tortuga marina, palmeras y tipografía 'Honduras' vertical. Disponibles en blanco y negro, personalizables con tu nombre, empresa o diseño propio. Impresión duradera que aguanta lavados.", highlights: ["Camiseta blanca desde L 200", "Camiseta negra desde L 280", "Diseños hondureños originales", "Personalización con logo o nombre"] },
  { title: "Camisetas Honduras minimalistas", tag: "Fiestas Patrias", type: "Iron-ons", subtitle: "Camisetas negras con mapa bordado 'Honduras' y camisetas blancas con collage patrio · pirámide, palmeras, guacamaya, tortuga, baleada y más", image: camisetasHonduras2.url, bg: "#ffffff", fit: "contain", description: "Camisetas patrióticas con dos estilos: la versión negra minimalista con firma 'Honduras' y mapa del país en el pecho, y la versión blanca con collage patrio (pirámide maya, palmeras, guacamaya, tortuga, baleada, bandera y frases hondureñas). Personalizables con tu marca o nombre.", highlights: ["Diseño minimalista con mapa de Honduras", "Collage patrio full color", "Blanco y negro disponibles", "Personalización con logo o nombre"] },
  { title: "Cuadro de Danza Fiestas Patrias", tag: "Fiestas Patrias", type: "Impresos", subtitle: "Banners, banderas, próceres patrios, camisetas sublimadas y más · tamaño y diseño a tu preferencia", image: fiestasPatriasCuadro.url, bg: "#f2ede4", fit: "contain", description: "Banners y cuadros patrios personalizados para las Fiestas Patrias. Diseños con danza folclórica, próceres, banderas y motivos hondureños. Tamaño y diseño totalmente a tu preferencia, ideales para centros educativos, empresas y eventos cívicos.", highlights: ["Banners y banderas full color", "Próceres patrios y motivos folclóricos", "Camisetas sublimadas disponibles", "Tamaño y diseño a tu preferencia"] },
  { title: "Próceres Patrios Troquelados", tag: "Fiestas Patrias", type: "PVC", subtitle: "Próceres mayores y menores troquelados · José Cecilio del Valle, Lempira, escudo nacional y más · perfectos para actos cívicos y escuelas", image: fiestasPatriasProceres.url, bg: "#ececec", fit: "contain", description: "Próceres patrios troquelados en PVC con impresión full color HD. Mayores y menores disponibles: José Cecilio del Valle, Lempira, Francisco Morazán, Dionisio de Herrera, el escudo nacional y más. Ideales para actos cívicos, decoración de escuelas, empresas y eventos de Fiestas Patrias.",  highlights: ["Próceres mayores y menores", "Troquelado en PVC resistente", "Impresión full color HD", "Tamaños personalizables"] },
  { title: "Stickers Troquelados para Cafés", tag: "Cafés & Negocios", type: "Stickers", subtitle: "Personalizá vitrinas y vasos con tu logo, slogan y temática de temporada · perfectos para el mes patrio y campañas especiales", image: stickerTroqueladoCafe.url, bg: "#ececec", fit: "contain", description: "Stickers troquelados para cafés y negocios. Personalizá tus vitrinas, ventanas y vasos con tu producto, slogan y temática de temporada. Ideales para campañas del mes patrio, promociones y decoración estacional.", highlights: ["Troquelado en la forma que quieras", "Vinil resistente a intemperie", "Personalización con logo y slogan", "Perfecto para vitrinas y vasos"] },
  
  { title: "Camisetas Estampadas Personalizadas", tag: "Camisetas & Textil", type: "Iron-ons", subtitle: "Disponible con estampado o sublimación · algodón, kiana, durazno, manga corta y manga larga · colores negro, blanco, rojo, naranja, rosado, amarillo, verde y azul", image: camisetasEstampadas.url, bg: "#ececec", fit: "contain", description: "Camisetas estampadas y sublimadas totalmente personalizadas con tu diseño, nombre, foto o logo. Ideales para cumpleaños, eventos, empresas, equipos y regalos. Amplia variedad de tipos de tela y colores disponibles.", highlights: ["Tipos: algodón, kiana, durazno, manga corta y manga larga", "Colores: negro, blanco, rojo, naranja, rosado, amarillo, verde y azul", "Estampado o sublimación full color", "Diseños personalizados con nombre, foto o logo"] },
  { title: "Rótulos de Medidas de Prevención", tag: "Señalética & Seguridad", type: "Rotulación", subtitle: "Rótulos en PVC y para pisos · medidas estándar y personalizados con tu logo · protección de alto tráfico para pisos", image: rotulosPrevencion.url, bg: "#ececec", fit: "contain", description: "Rótulos de medidas de prevención y señalética para negocios, oficinas, clínicas y espacios públicos. Rótulos en PVC en medidas estándar o personalizados con tu logo, y rótulos para pisos con protección de alto tráfico anti-deslizante.", highlights: ["Rótulos en PVC estándar o personalizados", "Rótulos para pisos con protección anti-tráfico", "Personalización con tu logo y marca", "Ideales para negocios, oficinas y clínicas"] },

  /* ---------- Libretas & Cuadernos ---------- */
  { title: "Libreta Amor · Corazones Rosa", tag: "Libretas & Planners", type: "Libretas", subtitle: "Portada rosa con corazones · interior a elección · espiral metálico premium", image: libretaCorazones.url, watermark: idealoLogoColor.url, bg: "#fce7f3", fit: "cover", description: "Libreta personalizada con portada full color y espiral metálico. Diseño 'Tú eres el proyecto más importante de tu vida'. Interior configurable (blanco, rayado, cuadriculado o punteado) y cantidad de páginas a elegir (50, 80, 100, 150 o 200).", highlights: ["Portada cartoncillo o cartón grueso", "Interior blanco, rayado, cuadriculado o punteado", "De 50 hasta 200 páginas", "Tamaños: Carta, A4, Legal, 12×18 y 11×18"] },
  { title: "Planner 2026 · Cerezas", tag: "Libretas & Planners", type: "Libretas", subtitle: "Planificador anual full color · portada cartón grueso · con calendario integrado", image: libretaPlanner.url, watermark: idealoLogoColor.url, bg: "#dcfce7", fit: "cover", description: "Planificador anual 2026 con calendario integrado, secciones para metas, hábitos y notas semanales. Portada full color con cartón grueso resistente. Personalizá con tu marca, colores y frases favoritas.", highlights: ["Calendario 2026 integrado", "Portada cartón grueso premium", "Diseño 100% personalizable", "Ideal como regalo corporativo"] },
  { title: "Libreta 'Fuerza y Dignidad' · Proverbios 31:25", tag: "Libretas & Frases", type: "Libretas", subtitle: "Portada amarilla con frase bíblica · texto rosa magenta · impresión full color", image: libretaFuerza.url, watermark: idealoLogoColor.url, bg: "#fef08a", fit: "cover", description: "Libreta con frase bíblica motivacional Proverbios 31:25. Portada amarilla vibrante con texto rosa magenta. Personalizala con tu versículo, frase o mensaje favorito.", highlights: ["Frase o versículo personalizable", "Impresión full color", "Espiral metálico resistente", "Ideal como regalo espiritual"] },
  { title: "Libreta 'El Señor es mi Fuerza' · Salmos 28:7", tag: "Libretas & Frases", type: "Libretas", subtitle: "Portada morada con texto blanco · cuadrícula punteada · formato cuadrado", image: libretaSalmo.url, watermark: idealoLogoColor.url, bg: "#e9d5ff", fit: "cover", description: "Libreta cuadrada con frase bíblica Salmos 28:7. Portada morada elegante con texto blanco y cuadrícula punteada de fondo. Cualquier versículo o mensaje personalizado disponible.", highlights: ["Frase o versículo a tu elección", "Formato cuadrado premium", "Papel interior a elegir", "Regalo espiritual perfecto"] },
  { title: "Libreta 'Vivimos por Fe' · 2 Corintios 5:7", tag: "Libretas & Frases", type: "Libretas", subtitle: "Portada celeste con texto morado · cuadrícula punteada · acabado premium", image: libretaFe.url, video: libretaVivimosFeDemo.url, watermark: idealoLogoColor.url, bg: "#bae6fd", fit: "cover", description: "Libreta con frase bíblica 2 Corintios 5:7. Portada celeste con texto morado vibrante. Perfecta como regalo espiritual, para devocionales o journaling.", highlights: ["Diseño y frase personalizable", "Portada cartoncillo premium", "Papel interior a elección", "Ideal para journaling y devocionales"] },
  { title: "Libreta 'Tu Futuro es Brillante' · Fe y Motivación", tag: "Libretas & Frases", type: "Libretas", subtitle: "Portada roja con corazones · frase motivacional · impresión full color", image: libretaFuturo.url, watermark: idealoLogoColor.url, bg: "#fecaca", fit: "cover", description: "Libreta motivacional con portada roja y corazones. Diseño 'Tu futuro es tan brillante como tu fe'. Perfecta como regalo, agenda personal o journal.", highlights: ["Frase motivacional personalizable", "Espiral metálico dorado", "Portada cartón grueso", "Ideal para regalos y agendas"] },
  { title: "Libreta 'Make Your Dreams Happen'", tag: "Libretas & Frases", type: "Libretas", subtitle: "Estilo minimalista · portada blanca con puntos rosa y naranja · espiral superior", image: libretaDreams.url, video: libretaDreamsDemo.url, watermark: idealoLogoColor.url, bg: "#fef3f2", fit: "cover", description: "Libreta minimalista tipo notepad con espiral superior. Diseño 'Make Your Dreams Happen Today' con puntos decorativos. Ideal para listas, notas rápidas y planning diario.", highlights: ["Espiral superior tipo notepad", "Diseño minimalista personalizable", "Papel bond o cuadriculado", "Perfecta para escritorio"] },
  { title: "Libreta Corporativa · EcoGaz / Enagasa / EcoAuto", tag: "Libretas Corporativas", type: "Libretas", subtitle: "Libreta corporativa personalizada con logos e identidad de marca · impresión full color", image: libretaEcoCover.url, watermark: idealoLogoColor.url, bg: "#86efac", fit: "cover", description: "Libreta corporativa personalizada con múltiples logos e identidad de marca. Portada full color y espiral resistente. Ideal para regalos a colaboradores, clientes y aliados estratégicos.", highlights: ["Múltiples logos en portada", "Impresión full color", "Cantidades desde 25 unidades", "Ideal para regalos corporativos"] },
  { title: "Libreta Corporativa · Interior Personalizado", tag: "Libretas Corporativas", type: "Libretas", subtitle: "Interior con encabezado corporativo, fecha y campo de tema · líneas guía", image: libretaEcoOpen.url, watermark: idealoLogoColor.url, bg: "#bbf7d0", fit: "cover", description: "Libreta corporativa con interior 100% personalizado: encabezado con logos, campo de tema, fecha y líneas guía. Perfecta para reuniones, capacitaciones y trabajo diario.", highlights: ["Interior personalizado con tu marca", "Encabezado, tema y fecha impresos", "Papel bond blanco de alta calidad", "Espiral doble resistente"] },
  { title: "Libreta 'Sueña, Planea y Construye' · Mi Agenda", tag: "Libretas & Frases", type: "Libretas", subtitle: "Portada rosa con corazones · frase motivacional · espiral metálico premium", image: libretaSuenaPlanea.url, watermark: idealoLogoColor.url, bg: "#fbcfe8", fit: "cover", description: "Agenda personalizada con portada rosa full color y espiral metálico. Diseño 'Sueña, planea y construye'. Interior configurable y cantidad de páginas a elegir.", highlights: ["Portada cartoncillo o cartón grueso", "Interior a elección", "De 50 hasta 200 páginas", "Diseño 100% personalizable"] },
  { title: "Libreta Stitch Azul", tag: "Libretas & Personajes", type: "Libretas", subtitle: "Portada azul con Stitch · diseño de personaje · espiral metálico premium", image: libretaStitchAzul.url, watermark: idealoLogoColor.url, bg: "#bfdbfe", fit: "cover", description: "Libreta con portada full color de Stitch. Podemos hacerla con cualquier personaje favorito, foto o diseño personalizado. Interior y páginas a elegir.", highlights: ["Cualquier personaje o diseño", "Portada cartón grueso", "Interior a elección", "Espiral metálico resistente"] },
  { title: "Libreta 'Mis Ideas' · Notepad Vertical", tag: "Libretas & Notepads", type: "Libretas", subtitle: "Notepad vertical con doble espiral · portada blanca minimalista con bombilla naranja", image: libretaMisIdeas.url, watermark: idealoLogoColor.url, bg: "#ffffff", fit: "cover", description: "Notepad vertical tipo bloc con doble espiral superior. Diseño minimalista 'Mis Ideas' con bombilla decorativa. Perfecto para brainstorming, notas rápidas y listas.", highlights: ["Doble espiral superior", "Formato vertical tipo bloc", "Diseño minimalista personalizable", "Ideal para brainstorming"] },
  { title: "Libreta 'Notas' Floral · Bloc Vertical", tag: "Libretas & Notepads", type: "Libretas", subtitle: "Portada floral con interior rayado y sección 'Importante' · doble espiral", image: libretaNotasPortada.url, extraImages: [libretaNotasInterior.url], watermark: idealoLogoColor.url, bg: "#fef9c3", fit: "cover", description: "Bloc de notas vertical con doble espiral superior. Portada floral premium con caligrafía 'Notas'. Interior con líneas guía, encabezado de días (LMMJVSD) y sección destacada 'Importante' en la parte inferior. Perfecto para agendar, listas y recordatorios.", highlights: ["Portada floral premium", "Interior rayado con días de la semana", "Sección 'Importante' destacada", "Doble espiral superior"] },
  { title: "Libreta 'Citas' Horizontal · Formato Agenda", tag: "Libretas & Agendas", type: "Libretas", subtitle: "Formato horizontal apaisado · portada rosa con tipografía elegante · espiral doble superior", image: libretaCitas.url, watermark: idealoLogoColor.url, bg: "#fbcfe8", fit: "cover", description: "Libreta de citas en formato horizontal apaisado. Portada rosa con tipografía serif elegante y detalles decorativos. Ideal para salones, clínicas, spas y profesionales que gestionan agenda de citas.", highlights: ["Formato horizontal apaisado", "Tipografía elegante personalizable", "Doble espiral superior", "Ideal para salones y clínicas"] },
  { title: "Calendario Idealo 2026", tag: "Calendarios & Corporativo", type: "Libretas", subtitle: "Calendario de escritorio 2026 · portada full color · interior mensual ilustrado", image: calendario2026Portada.url, extraImages: [calendario2026Enero.url], video: libretaVideoDemo.url, watermark: idealoLogoColor.url, bg: "#3b82f6", fit: "cover", description: "Calendario de escritorio 2026 con espiral horizontal. Portada full color con tipografía tipo diseño gráfico y páginas interiores ilustradas mes por mes (ENERO, FEBRERO...). Ideal como regalo corporativo, para escritorios y oficinas.", highlights: ["12 meses ilustrados full color", "Espiral horizontal resistente", "Formato de escritorio tipo caballete", "Personalizable con tu marca"] },
  { title: "Libreta Stitch · 'Ohana Means Family'", tag: "Libretas & Personajes", type: "Libretas", subtitle: "Portada azul con Stitch y margaritas · frase 'Ohana Means Family' · espiral metálico", image: libretaOhanaStitch.url, video: libretaVideoDemo.url, watermark: idealoLogoColor.url, bg: "#93c5fd", fit: "cover", description: "Libreta con portada full color de Stitch rodeado de margaritas y la frase 'Ohana Means Family'. Podemos personalizar con cualquier personaje, frase o foto que quieras. Interior y páginas a elección.", highlights: ["Diseño personalizable con cualquier personaje", "Portada cartón grueso premium", "Espiral metálico resistente", "Interior configurable"] },
  { title: "Libreta 'Grandes Planes' · Bloques de Color", tag: "Libretas & Planners", type: "Libretas", subtitle: "Portada full color con bloques orgánicos naranja, rojo y magenta · espiral metálico", image: libretaGrandesPlanes.url, watermark: idealoLogoColor.url, bg: "#f97316", fit: "cover", description: "Libreta 'Grandes Planes' con portada full color de bloques orgánicos en naranja, rojo, magenta y verde lima. Tipografía elegante. Ideal para planificación anual, metas y sueños. Personalizable con tu diseño, frase o marca.", highlights: ["Portada cartón grueso premium", "Diseño 100% personalizable", "Interior a elección", "Espiral metálico resistente"] },
  { title: "Álbum 'Momentos' · Pequeños Momentos, Grandes Memorias", tag: "Libretas & Álbumes", type: "Libretas", subtitle: "Álbum horizontal apaisado · portada magenta con caligrafía blanca · espiral premium", image: libretaMomentos.url, video: libretaMomentosDemo.url, watermark: idealoLogoColor.url, bg: "#ec4899", fit: "cover", description: "Álbum de recuerdos en formato horizontal apaisado. Portada magenta full color con la frase 'Pequeños momentos, grandes memorias'. Perfecto como regalo para aniversarios, bodas, cumpleaños y momentos familiares.", highlights: ["Formato horizontal apaisado", "Portada cartón grueso premium", "Interior para fotos y notas", "Diseño 100% personalizable"] },
  { title: "Álbum 'Memorias' · Portada Negra Line Art Dorado", tag: "Libretas & Álbumes", type: "Libretas", subtitle: "Álbum horizontal · portada negra con ilustración line art dorada de pareja · caligrafía elegante", image: libretaMemorias.url, video: libretaMemoriasDemo.url, watermark: idealoLogoColor.url, bg: "#0a0a0a", fit: "cover", description: "Álbum 'Memorias' en formato horizontal apaisado. Portada negra premium con ilustración line art dorada de una pareja y corazones. Caligrafía elegante 'Memorias'. Ideal como regalo para aniversarios, bodas y parejas.", highlights: ["Portada negra premium con foil dorado", "Ilustración line art personalizable", "Formato apaisado tipo álbum", "Interior configurable para fotos"] },
];

export const projects: Project[] = raw.map((p) => ({ ...p, slug: slugify(p.title) }));

export const getProjectBySlug = (slug: string): Project | undefined =>
  projects.find((p) => p.slug === slug);
