/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as EventosRouteImport } from './routes/eventos'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EventosIndexRouteImport } from './routes/eventos.index'
import { Route as EventosCategoriaIndexRouteImport } from './routes/eventos.$categoria.index'
import { Route as EventosCategoriaProductoRouteImport } from './routes/eventos.$categoria.$producto'

const EventosRoute = EventosRouteImport.update({
  id: '/eventos',
  path: '/eventos',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EventosIndexRoute = EventosIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EventosRoute,
} as any)
const EventosCategoriaIndexRoute = EventosCategoriaIndexRouteImport.update({
  id: '/$categoria/',
  path: '/$categoria/',
  getParentRoute: () => EventosRoute,
} as any)
const EventosCategoriaProductoRoute =
  EventosCategoriaProductoRouteImport.update({
    id: '/$categoria/$producto',
    path: '/$categoria/$producto',
    getParentRoute: () => EventosRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/eventos': typeof EventosRouteWithChildren
  '/eventos/': typeof EventosIndexRoute
  '/eventos/$categoria/$producto': typeof EventosCategoriaProductoRoute
  '/eventos/$categoria/': typeof EventosCategoriaIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/eventos': typeof EventosIndexRoute
  '/eventos/$categoria/$producto': typeof EventosCategoriaProductoRoute
  '/eventos/$categoria': typeof EventosCategoriaIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/eventos': typeof EventosRouteWithChildren
  '/eventos/': typeof EventosIndexRoute
  '/eventos/$categoria/$producto': typeof EventosCategoriaProductoRoute
  '/eventos/$categoria/': typeof EventosCategoriaIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/eventos'
    | '/eventos/'
    | '/eventos/$categoria/$producto'
    | '/eventos/$categoria/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/eventos' | '/eventos/$categoria/$producto' | '/eventos/$categoria'
  id:
    | '__root__'
    | '/'
    | '/eventos'
    | '/eventos/'
    | '/eventos/$categoria/$producto'
    | '/eventos/$categoria/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EventosRoute: typeof EventosRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/eventos': {
      id: '/eventos'
      path: '/eventos'
      fullPath: '/eventos'
      preLoaderRoute: typeof EventosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/eventos/': {
      id: '/eventos/'
      path: '/'
      fullPath: '/eventos/'
      preLoaderRoute: typeof EventosIndexRouteImport
      parentRoute: typeof EventosRoute
    }
    '/eventos/$categoria/': {
      id: '/eventos/$categoria/'
      path: '/$categoria'
      fullPath: '/eventos/$categoria/'
      preLoaderRoute: typeof EventosCategoriaIndexRouteImport
      parentRoute: typeof EventosRoute
    }
    '/eventos/$categoria/$producto': {
      id: '/eventos/$categoria/$producto'
      path: '/$categoria/$producto'
      fullPath: '/eventos/$categoria/$producto'
      preLoaderRoute: typeof EventosCategoriaProductoRouteImport
      parentRoute: typeof EventosRoute
    }
  }
}

interface EventosRouteChildren {
  EventosIndexRoute: typeof EventosIndexRoute
  EventosCategoriaProductoRoute: typeof EventosCategoriaProductoRoute
  EventosCategoriaIndexRoute: typeof EventosCategoriaIndexRoute
}

const EventosRouteChildren: EventosRouteChildren = {
  EventosIndexRoute: EventosIndexRoute,
  EventosCategoriaProductoRoute: EventosCategoriaProductoRoute,
  EventosCategoriaIndexRoute: EventosCategoriaIndexRoute,
}

const EventosRouteWithChildren =
  EventosRoute._addFileChildren(EventosRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EventosRoute: EventosRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
