/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as EventosRouteImport } from './routes/eventos'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EventosCategoriaRouteImport } from './routes/eventos.$categoria'

const EventosRoute = EventosRouteImport.update({
  id: '/eventos',
  path: '/eventos',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EventosCategoriaRoute = EventosCategoriaRouteImport.update({
  id: '/$categoria',
  path: '/$categoria',
  getParentRoute: () => EventosRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/eventos': typeof EventosRouteWithChildren
  '/eventos/$categoria': typeof EventosCategoriaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/eventos': typeof EventosRouteWithChildren
  '/eventos/$categoria': typeof EventosCategoriaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/eventos': typeof EventosRouteWithChildren
  '/eventos/$categoria': typeof EventosCategoriaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/eventos' | '/eventos/$categoria'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/eventos' | '/eventos/$categoria'
  id: '__root__' | '/' | '/eventos' | '/eventos/$categoria'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EventosRoute: typeof EventosRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/eventos': {
      id: '/eventos'
      path: '/eventos'
      fullPath: '/eventos'
      preLoaderRoute: typeof EventosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/eventos/$categoria': {
      id: '/eventos/$categoria'
      path: '/$categoria'
      fullPath: '/eventos/$categoria'
      preLoaderRoute: typeof EventosCategoriaRouteImport
      parentRoute: typeof EventosRoute
    }
  }
}

interface EventosRouteChildren {
  EventosCategoriaRoute: typeof EventosCategoriaRoute
}

const EventosRouteChildren: EventosRouteChildren = {
  EventosCategoriaRoute: EventosCategoriaRoute,
}

const EventosRouteWithChildren =
  EventosRoute._addFileChildren(EventosRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EventosRoute: EventosRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
